### ISSUE TITLE
Rename: the App.js and app.js

### ISSUE THREAD

**Issue by negue** [cmgriffing/create-streamdeck-plugin#3]
I think these two `App.js` and `app.js` sometimes confuse me while working on it. 😅 

Could be one of it maybe called "ConfigView" ?

**Comment by cmgriffing** [comment]
Thanks. I finally made that change in this commit:
https://github.com/cmgriffing/create-streamdeck-plugin/commit/5c9dcbd86f00b67fcea6339e7c62682c1874925e

I have also released version 0.0.18 to npm with this change.
