### ISSUE TITLE
Generator does not update the title of the prop inspector

### ISSUE THREAD

**Issue by Hacksore** [cmgriffing/create-streamdeck-plugin#5]
As you can see this isn't right :)

![image](https://user-images.githubusercontent.com/996134/111871156-bca42980-8956-11eb-960c-f311503ffc9e.png)

https://github.com/cmgriffing/create-streamdeck-plugin/blob/master/templates/base/example/public/propertyinspector/index.html#L11

**Comment by cmgriffing** [comment]
Sorry, I forgot all about this and it got buried by dependabot notifications.

I will fix this up in a few days.

**Comment by Hacksore** [comment]
I just close old issues as they show up on my recents 😬

**Comment by cmgriffing** [comment]
No worries. Thanks again for reporting it.

I have fixed it in this commit:
https://github.com/cmgriffing/create-streamdeck-plugin/commit/c4c7c151430b43c7c922954ba2c67d653bf736ae#diff-08a7c9598d979d89fecedb2a4087b5c84fe4722cbe2ce55942fab7e301625ed1

And I have published version 0.0.17 of the cli tool to npm.
